# Travis-CI Build for OpenRA
# see travis-ci.org for details

dist: xenial
language: csharp
mono: 5.20.1

cache:
  directories:
  - thirdparty/download

addons:
  apt:
    packages:
    - lua5.1
    - dpkg
    - markdown
    - zlib1g-dev
    - libbz2-dev
    - cmake
    - genisoimage
    - fakeroot
    - zsync

# Environment variables
env:
  secure: "C0+Hlfa0YGErxUuWV00Tj6p45otC/D3YwYFuLpi2mj1rDFn/4dgh5WRngjvdDBVbXJ3duaZ78jPHWm1jr7vn2jqj9yETsCIK9psWd38ep/FEBM0SDr6MUD89OuXk/YyvxJAE+UXF6bXg7giey09g/CwBigjMW7ynET3wNAWPHPs="

# Fetch dependencies
# Run the build script
# Check source code with StyleCop
# call OpenRA to check for YAML errors
# Run the NUnit tests
script:
 - travis_retry make all-dependencies
 - make all

# Only watch the development branch and tagged release.
branches:
 only:
   - /^release-.*$/
   - /^playtest-.*$/
   - /^pkgtest-.*$/
   - /^prep-.*$/
   - bleed

before_deploy:
 - wget http://mirrors.kernel.org/ubuntu/pool/universe/n/nsis/nsis-common_3.03-2_all.deb
 - wget http://mirrors.kernel.org/ubuntu/pool/universe/n/nsis/nsis_3.03-2_amd64.deb
 - sudo dpkg -i nsis-common_3.03-2_all.deb
 - sudo dpkg -i nsis_3.03-2_amd64.deb
 - makensis -VERSION
 - export PATH=$PATH:$HOME/usr/bin
 - DOTVERSION=`echo ${TRAVIS_TAG} | sed "s/-/\\./g"`
 - cd packaging
 - mkdir build
 - ./package-all.sh ${TRAVIS_TAG} ${PWD}/build/
deploy:
  provider: releases
  api_key:
    secure: BzLdjZHvDqd5jyyHS8KK8zrNiXEIQiGRS/RMfqK6LuFPC4mXYDE4C/0oLPe93ULtai6LgUUkwB+zKq4lDV109EBO8Xp0jXKdDLLsepGU5xRLt3Z2tT4Zj+Nx6daVjAJe1MaKO5Zo5ODi8kBploRnPCffA8AMzOyQ+OwwJNlcRSs=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: pchote/OpenRA
