# Travis-CI Build for OpenRA
# see travis-ci.org for details

language: csharp
mono: 6.4.0

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      if: tag IS present
      osx_image: xcode10

cache:
  directories:
  - thirdparty/download

addons:
  apt:
    packages:
    - lua5.1
    - dpkg
    - zsync
    - markdown

# Environment variables
env:
  secure: "C0+Hlfa0YGErxUuWV00Tj6p45otC/D3YwYFuLpi2mj1rDFn/4dgh5WRngjvdDBVbXJ3duaZ78jPHWm1jr7vn2jqj9yETsCIK9psWd38ep/FEBM0SDr6MUD89OuXk/YyvxJAE+UXF6bXg7giey09g/CwBigjMW7ynET3wNAWPHPs="

# Fetch dependencies
# Run the build script
# Check source code with StyleCop
# call OpenRA to check for YAML errors
# Run the NUnit tests
script:
 - make all
 - test "$TRAVIS_OS_NAME" == "linux" && make check || echo "Skipping check"
 - test "$TRAVIS_OS_NAME" == "linux" && make check-scripts || echo "Skipping scripts check"
 - test "$TRAVIS_OS_NAME" == "linux" && make test || echo "Skipping tests"
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     mono ~/.nuget/packages/nunit.consolerunner/3.11.1/tools/nunit3-console.exe --noresult OpenRA.Test.dll;
   fi

# Only watch the development branch and tagged release.
branches:
 only:
   - /^release-.*$/
   - /^playtest-.*$/
   - /^pkgtest-.*$/
   - /^prep-.*$/
   - /^devtest-.*$/
   - bleed

before_deploy:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis-common_3.04-1_all.deb;
     wget https://mirrors.edge.kernel.org/ubuntu/pool/universe/n/nsis/nsis_3.04-1_amd64.deb;
     sudo dpkg -i nsis-common_3.04-1_all.deb;
     sudo dpkg -i nsis_3.04-1_amd64.deb;
     cd packaging && ./update-wiki.sh ${TRAVIS_TAG} && cd ..;
   fi;
 - export PATH=$PATH:$HOME/usr/bin
 - DOTVERSION=`echo ${TRAVIS_TAG} | sed "s/-/\\./g"`
 - cd packaging
 - mkdir build
 - ./package-all.sh release-20200503 ${PWD}/build/

deploy:
  provider: releases
  api_key:
    secure: BzLdjZHvDqd5jyyHS8KK8zrNiXEIQiGRS/RMfqK6LuFPC4mXYDE4C/0oLPe93ULtai6LgUUkwB+zKq4lDV109EBO8Xp0jXKdDLLsepGU5xRLt3Z2tT4Zj+Nx6daVjAJe1MaKO5Zo5ODi8kBploRnPCffA8AMzOyQ+OwwJNlcRSs=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: pchote/OpenRA
