name: Continuous Integration

on:
  push:
    branches: [ bleed, gh-actions ]

  pull_request:
    branches: [ bleed ]

  workflow_dispatch:

jobs:
  linux-mono:
    name: Linux (mono)
    runs-on: ubuntu-16.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Check Code
        run: |
          mono --version
          make check
          mono ~/.nuget/packages/nunit.consolerunner/3.11.1/tools/nunit3-console.exe --noresult bin/OpenRA.Test.dll

      - name: Check Mods
        run: |
          sudo apt-get install lua5.1
          make check-scripts
          make test

  windows:
    name: Windows (Framework 4.7)
    runs-on: windows-2019

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Check Code
        shell: powershell
        run: |
          .\make.ps1 check
          Invoke-Expression "$home\.nuget\packages\nunit.consolerunner\3.11.1\tools\nunit3-console.exe --noresult bin/OpenRA.Test.dll"

      - name: Check Mods
        run: |
          chocolatey install lua --version 5.1.5.52
          $ENV:Path = $ENV:Path + ";C:\Program Files (x86)\Lua\5.1\"
          .\make.ps1 check-scripts
          .\make.ps1 test
